       Table: accounting_ledger
CREATE TABLE `accounting_ledger` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `transaction_ref` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Unique transaction reference: TXN-20260113-XXXXX',
  `purchase_id` bigint unsigned DEFAULT NULL,
  `merchant_purchase_id` bigint unsigned DEFAULT NULL,
  `from_party_id` bigint unsigned NOT NULL,
  `to_party_id` bigint unsigned NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `monetary_unit_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'SAR',
  `transaction_type` enum('debt','collection','settlement','fee','refund','reversal','adjustment') COLLATE utf8mb4_unicode_ci NOT NULL,
  `entry_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Specific entry type: SALE_REVENUE, COMMISSION_EARNED, TAX_COLLECTED, etc.',
  `direction` enum('DEBIT','CREDIT') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CREDIT',
  `description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description_ar` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `metadata` json DEFAULT NULL COMMENT 'Additional data: payment_method, tracking_number, etc',
  `status` enum('pending','completed','cancelled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `debt_status` enum('PENDING','SETTLED','CANCELLED','REVERSED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `original_entry_id` bigint unsigned DEFAULT NULL,
  `transaction_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `settled_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `settled_by` bigint unsigned DEFAULT NULL,
  `settlement_batch_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `accounting_ledger_transaction_ref_unique` (`transaction_ref`),
  KEY `accounting_ledger_purchase_id_index` (`purchase_id`),
  KEY `accounting_ledger_merchant_purchase_id_index` (`merchant_purchase_id`),
  KEY `accounting_ledger_transaction_type_index` (`transaction_type`),
  KEY `accounting_ledger_status_index` (`status`),
  KEY `accounting_ledger_transaction_date_index` (`transaction_date`),
  KEY `accounting_ledger_from_party_id_to_party_id_index` (`from_party_id`,`to_party_id`),
  KEY `accounting_ledger_to_party_id_from_party_id_index` (`to_party_id`,`from_party_id`),
  KEY `accounting_ledger_settlement_batch_id_foreign` (`settlement_batch_id`),
  KEY `accounting_ledger_original_entry_id_foreign` (`original_entry_id`),
  KEY `accounting_ledger_entry_type_index` (`entry_type`),
  KEY `accounting_ledger_debt_status_index` (`debt_status`),
  KEY `accounting_ledger_direction_index` (`direction`),
  CONSTRAINT `accounting_ledger_from_party_id_foreign` FOREIGN KEY (`from_party_id`) REFERENCES `account_parties` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `accounting_ledger_original_entry_id_foreign` FOREIGN KEY (`original_entry_id`) REFERENCES `accounting_ledger` (`id`) ON DELETE SET NULL,
  CONSTRAINT `accounting_ledger_settlement_batch_id_foreign` FOREIGN KEY (`settlement_batch_id`) REFERENCES `settlement_batches` (`id`) ON DELETE SET NULL,
  CONSTRAINT `accounting_ledger_to_party_id_foreign` FOREIGN KEY (`to_party_id`) REFERENCES `account_parties` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
