       Table: catalog_items
CREATE TABLE `catalog_items` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `part_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `weight` decimal(10,2) DEFAULT '1.00',
  `label_en` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `label_ar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attributes` text COLLATE utf8mb4_unicode_ci,
  `name` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` text COLLATE utf8mb4_unicode_ci,
  `photo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'LargePNG/SVG/noimage.png',
  `thumbnail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'SmallPNG/SVG/noimage.png',
  `views` int unsigned NOT NULL DEFAULT '0',
  `tags` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_meta` tinyint NOT NULL DEFAULT '0',
  `meta_tag` text COLLATE utf8mb4_unicode_ci,
  `meta_description` text COLLATE utf8mb4_unicode_ci,
  `youtube` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `measure` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hot` tinyint unsigned NOT NULL DEFAULT '0',
  `latest` tinyint unsigned NOT NULL DEFAULT '0',
  `sale` tinyint NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `cross_items` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_part_number` (`part_number`) USING BTREE,
  KEY `idx_catalog_items_part_number` (`part_number`) USING BTREE,
  FULLTEXT KEY `name` (`name`),
  FULLTEXT KEY `attributes` (`attributes`)
) ENGINE=InnoDB AUTO_INCREMENT=679169 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
