-- Schema for table: home_page_themes
-- Exported: 2026-01-03 04:17:45

DROP TABLE IF EXISTS `home_page_themes`;

CREATE TABLE `home_page_themes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `layout` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'default',
  `show_slider` tinyint(1) NOT NULL DEFAULT '1',
  `show_hero_search` tinyint(1) NOT NULL DEFAULT '1',
  `show_brands` tinyint(1) NOT NULL DEFAULT '1',
  `show_categories` tinyint(1) NOT NULL DEFAULT '1',
  `show_arrival` tinyint(1) NOT NULL DEFAULT '1',
  `show_featured_items` tinyint(1) NOT NULL DEFAULT '1',
  `show_deal_of_day` tinyint(1) NOT NULL DEFAULT '1',
  `show_top_rated` tinyint(1) NOT NULL DEFAULT '1',
  `show_big_save` tinyint(1) NOT NULL DEFAULT '1',
  `show_trending` tinyint(1) NOT NULL DEFAULT '1',
  `show_best_sellers` tinyint(1) NOT NULL DEFAULT '1',
  `show_blogs` tinyint(1) NOT NULL DEFAULT '1',
  `show_services` tinyint(1) NOT NULL DEFAULT '1',
  `show_newsletter` tinyint(1) NOT NULL DEFAULT '1',
  `order_slider` int NOT NULL DEFAULT '1',
  `order_brands` int NOT NULL DEFAULT '2',
  `order_categories` int NOT NULL DEFAULT '3',
  `order_arrival` int NOT NULL DEFAULT '4',
  `order_featured_items` int NOT NULL DEFAULT '5',
  `order_deal_of_day` int NOT NULL DEFAULT '6',
  `order_top_rated` int NOT NULL DEFAULT '7',
  `order_big_save` int NOT NULL DEFAULT '8',
  `order_trending` int NOT NULL DEFAULT '9',
  `order_best_sellers` int NOT NULL DEFAULT '10',
  `order_blogs` int NOT NULL DEFAULT '11',
  `order_services` int NOT NULL DEFAULT '12',
  `order_newsletter` int NOT NULL DEFAULT '13',
  `title_brands` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_categories` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_arrival` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_featured_items` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_deal_of_day` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_top_rated` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_big_save` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_trending` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_best_sellers` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title_blogs` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `count_featured_items` int NOT NULL DEFAULT '8',
  `count_top_rated` int NOT NULL DEFAULT '6',
  `count_big_save` int NOT NULL DEFAULT '6',
  `count_trending` int NOT NULL DEFAULT '6',
  `count_best_sellers` int NOT NULL DEFAULT '8',
  `count_blogs` int NOT NULL DEFAULT '3',
  `settings` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `home_page_themes_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
