       Table: home_page_themes
CREATE TABLE `home_page_themes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '0',
  `layout` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'default',
  `show_hero_search` tinyint(1) NOT NULL DEFAULT '1',
  `show_brands` tinyint(1) NOT NULL DEFAULT '1',
  `show_categories` tinyint(1) NOT NULL DEFAULT '1',
  `show_arrival` tinyint(1) NOT NULL DEFAULT '1',
  `show_blogs` tinyint(1) NOT NULL DEFAULT '1',
  `show_capabilities` tinyint(1) NOT NULL DEFAULT '1',
  `show_newsletter` tinyint(1) NOT NULL DEFAULT '1',
  `order_brands` int NOT NULL DEFAULT '2',
  `order_categories` int NOT NULL DEFAULT '3',
  `order_arrival` int NOT NULL DEFAULT '4',
  `order_blogs` int NOT NULL DEFAULT '11',
  `order_capabilities` int NOT NULL DEFAULT '12',
  `order_newsletter` int NOT NULL DEFAULT '13',
  `name_brands` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_categories` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_blogs` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `count_blogs` int NOT NULL DEFAULT '3',
  `count_categories` tinyint unsigned NOT NULL DEFAULT '12',
  `settings` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `home_page_themes_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
