       Table: merchant_items
CREATE TABLE `merchant_items` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `catalog_item_id` int unsigned NOT NULL,
  `user_id` int unsigned NOT NULL,
  `merchant_branch_id` bigint NOT NULL,
  `quality_brand_id` bigint unsigned DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `previous_price` decimal(10,2) DEFAULT NULL,
  `stock` int DEFAULT NULL,
  `whole_sell_qty` text COLLATE utf8mb4_unicode_ci,
  `whole_sell_discount` text COLLATE utf8mb4_unicode_ci,
  `preordered` tinyint NOT NULL DEFAULT '0',
  `minimum_qty` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stock_check` int NOT NULL DEFAULT '0',
  `status` tinyint unsigned NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ship` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item_condition` tinyint(1) NOT NULL DEFAULT '2',
  `details` text COLLATE utf8mb4_unicode_ci,
  `policy` text COLLATE utf8mb4_unicode_ci,
  `item_type` enum('normal','affiliate') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal',
  `affiliate_link` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_catalog_item_user` (`catalog_item_id`,`user_id`,`merchant_branch_id`,`quality_brand_id`,`item_condition`),
  KEY `fk_mi_user` (`user_id`),
  KEY `mi_item_type` (`item_type`),
  KEY `mi_branch_id_index` (`merchant_branch_id`),
  KEY `idx_mi_quality_brand` (`quality_brand_id`),
  CONSTRAINT `fk_mi_catalog_item` FOREIGN KEY (`catalog_item_id`) REFERENCES `catalog_items` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_mi_quality_brand` FOREIGN KEY (`quality_brand_id`) REFERENCES `quality_brands` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_mi_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `merchant_items_merchant_branch_id_foreign` FOREIGN KEY (`merchant_branch_id`) REFERENCES `merchant_branches` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=122419 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
