-- Schema for table: merchant_items
-- Exported: 2026-01-07 23:59:03

DROP TABLE IF EXISTS `merchant_items`;

CREATE TABLE `merchant_items` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `catalog_item_id` int unsigned NOT NULL,
  `user_id` int unsigned NOT NULL,
  `brand_quality_id` bigint unsigned NOT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `previous_price` decimal(10,2) DEFAULT NULL,
  `stock` int DEFAULT NULL,
  `is_discount` tinyint NOT NULL DEFAULT '0',
  `discount_date` date DEFAULT NULL,
  `whole_sell_qty` text COLLATE utf8mb4_unicode_ci,
  `whole_sell_discount` text COLLATE utf8mb4_unicode_ci,
  `preordered` tinyint NOT NULL DEFAULT '0',
  `minimum_qty` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stock_check` int NOT NULL DEFAULT '0',
  `popular` int NOT NULL DEFAULT '0',
  `status` tinyint unsigned NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_popular` int NOT NULL DEFAULT '0',
  `licence_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `license_qty` text COLLATE utf8mb4_unicode_ci,
  `license` text COLLATE utf8mb4_unicode_ci,
  `ship` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item_condition` tinyint(1) NOT NULL DEFAULT '2',
  `color_all` text COLLATE utf8mb4_unicode_ci,
  `color_price` text COLLATE utf8mb4_unicode_ci,
  `details` text COLLATE utf8mb4_unicode_ci,
  `policy` text COLLATE utf8mb4_unicode_ci,
  `features` text COLLATE utf8mb4_unicode_ci,
  `colors` text COLLATE utf8mb4_unicode_ci,
  `size` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `size_qty` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal',
  `size_price` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `affiliate_link` text COLLATE utf8mb4_unicode_ci,
  `featured` tinyint unsigned NOT NULL DEFAULT '0',
  `top` tinyint unsigned NOT NULL DEFAULT '0',
  `big` tinyint unsigned NOT NULL DEFAULT '0',
  `trending` tinyint NOT NULL DEFAULT '0',
  `best` tinyint unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_catalog_item_user` (`catalog_item_id`,`user_id`,`brand_quality_id`),
  KEY `fk_mi_user` (`user_id`),
  KEY `idx_mi_brand_quality` (`brand_quality_id`),
  KEY `mi_product_type` (`item_type`),
  CONSTRAINT `fk_mi_brand_quality` FOREIGN KEY (`brand_quality_id`) REFERENCES `brand_qualities` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_mi_catalog_item` FOREIGN KEY (`catalog_item_id`) REFERENCES `catalog_items` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_mi_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1524365 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
