       Table: merchant_purchases
CREATE TABLE `merchant_purchases` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `purchase_id` int NOT NULL,
  `cart` json DEFAULT NULL,
  `qty` int NOT NULL,
  `price` double NOT NULL,
  `commission_amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `tax_amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `shipping_cost` decimal(10,2) NOT NULL DEFAULT '0.00',
  `courier_fee` decimal(10,2) NOT NULL DEFAULT '0.00',
  `platform_shipping_fee` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Platform shipping fee (if shipping_owner_id = 0)',
  `net_amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `merchant_owes_platform` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Amount merchant owes platform (when merchant receives payment directly)',
  `platform_owes_merchant` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT 'Amount platform owes merchant (when platform receives payment)',
  `courier_owes_platform` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Amount courier owes to platform (if platform gateway)',
  `shipping_company_owes_merchant` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Amount shipping company owes to merchant (COD collected)',
  `shipping_company_owes_platform` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Amount shipping company owes to platform (if platform gateway)',
  `cod_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Total COD amount (purchase + delivery fee)',
  `money_holder` enum('platform','merchant','courier','shipping_company','pending') NOT NULL DEFAULT 'pending' COMMENT 'Entity currently holding the payment',
  `delivery_method` enum('local_courier','shipping_company','pickup','digital','none') DEFAULT NULL COMMENT 'How the order is delivered',
  `delivery_provider` varchar(100) DEFAULT NULL COMMENT 'Specific provider: courier_id or tryoto/aramex/etc',
  `collection_status` enum('not_applicable','pending','collected','failed') NOT NULL DEFAULT 'not_applicable' COMMENT 'COD collection status',
  `collected_at` timestamp NULL DEFAULT NULL COMMENT 'When COD was collected',
  `collected_by` varchar(100) DEFAULT NULL COMMENT 'Who collected COD (courier_id or shipping_company_name)',
  `payment_type` enum('merchant','platform') NOT NULL DEFAULT 'platform',
  `shipping_type` enum('merchant','platform','courier','pickup') DEFAULT NULL,
  `money_received_by` enum('merchant','platform','courier') NOT NULL DEFAULT 'platform',
  `payment_owner_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Owner of payment gateway: 0=platform, else=merchant',
  `shipping_owner_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT 'Owner of shipping service: 0=platform, else=merchant',
  `payment_method` varchar(20) DEFAULT NULL COMMENT 'Payment method: cod or online',
  `payment_gateway_id` int unsigned DEFAULT NULL,
  `shipping_id` int unsigned DEFAULT NULL,
  `courier_id` int unsigned DEFAULT NULL,
  `merchant_branch_id` int unsigned DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `purchase_number` varchar(191) NOT NULL,
  `status` enum('pending','processing','completed','declined','on delivery') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `settlement_status` enum('unsettled','pending','settled') NOT NULL DEFAULT 'unsettled',
  `settled_at` timestamp NULL DEFAULT NULL,
  `merchant_settlement_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `mp_payment_owner_idx` (`payment_owner_id`),
  KEY `mp_shipping_owner_idx` (`shipping_owner_id`),
  KEY `mp_balance_idx` (`merchant_owes_platform`,`platform_owes_merchant`),
  KEY `merchant_purchases_money_holder_index` (`money_holder`),
  KEY `merchant_purchases_collection_status_index` (`collection_status`),
  KEY `merchant_purchases_settlement_status_money_holder_index` (`settlement_status`,`money_holder`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1
