CREATE TABLE `newcategories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `brand_id` bigint unsigned NOT NULL,
  `brand_region_id` bigint unsigned NOT NULL,
  `catalog_id` bigint unsigned NOT NULL,
  `parent_id` bigint unsigned DEFAULT NULL,
  `level` tinyint unsigned NOT NULL,
  `spec_key` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `parents_key` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `full_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `formatted_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Applicability` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `label_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `label_ar` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `thumbnail` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `images` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_newcategories_unique` (`parent_id`,`brand_region_id`,`catalog_id`,`full_code`),
  KEY `brand_region_id` (`brand_region_id`),
  KEY `brand_id` (`brand_id`),
  KEY `catalog_id` (`catalog_id`),
  KEY `idx_newcategories_level_fullcode` (`level`,`full_code`(50)),
  KEY `idx_nc_catalog_brand_level` (`catalog_id`,`brand_id`,`level`),
  KEY `idx_nc_full_code` (`full_code`),
  KEY `idx_nc_spec_key` (`catalog_id`,`spec_key`,`level`),
  CONSTRAINT `fk_nc_brand` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`),
  CONSTRAINT `fk_nc_brand_region` FOREIGN KEY (`brand_region_id`) REFERENCES `brand_regions` (`id`),
  CONSTRAINT `fk_nc_catalog` FOREIGN KEY (`catalog_id`) REFERENCES `catalogs` (`id`),
  CONSTRAINT `fk_nc_parent` FOREIGN KEY (`parent_id`) REFERENCES `newcategories` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=238935 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
