       Table: shipment_trackings
CREATE TABLE `shipment_trackings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `purchase_id` int unsigned NOT NULL,
  `merchant_id` int unsigned NOT NULL,
  `shipping_id` int unsigned DEFAULT NULL,
  `integration_type` enum('api','manual') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'manual',
  `provider` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tracking_number` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `external_shipment_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `company_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status_ar` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_en` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `message` text COLLATE utf8mb4_unicode_ci,
  `message_ar` text COLLATE utf8mb4_unicode_ci,
  `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `occurred_at` timestamp NULL DEFAULT NULL,
  `source` enum('api','merchant','system','operator') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'system',
  `raw_payload` json DEFAULT NULL,
  `awb_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `shipping_cost` decimal(10,2) DEFAULT NULL,
  `cod_amount` decimal(10,2) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `shipment_trackings_purchase_id_index` (`purchase_id`),
  KEY `shipment_trackings_merchant_id_index` (`merchant_id`),
  KEY `shipment_trackings_shipping_id_index` (`shipping_id`),
  KEY `shipment_trackings_tracking_number_index` (`tracking_number`),
  KEY `shipment_trackings_external_shipment_id_index` (`external_shipment_id`),
  KEY `shipment_trackings_status_index` (`status`),
  KEY `shipment_trackings_integration_type_index` (`integration_type`),
  KEY `shipment_trackings_provider_index` (`provider`),
  KEY `shipment_trackings_occurred_at_index` (`occurred_at`),
  KEY `shipment_trackings_purchase_id_merchant_id_index` (`purchase_id`,`merchant_id`),
  KEY `shipment_trackings_tracking_number_status_index` (`tracking_number`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
