       Table: vin_decoded_cache
CREATE TABLE `vin_decoded_cache` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `vin` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `brand_id` bigint unsigned DEFAULT NULL,
  `brand_region_id` bigint unsigned DEFAULT NULL,
  `catalog_id` bigint unsigned DEFAULT NULL,
  `catalogCode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `modelCode` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `buildDate` date DEFAULT NULL,
  `modelBeginDate` date DEFAULT NULL,
  `modelEndDate` date DEFAULT NULL,
  `shortName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `catalogType` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dataRegion` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `catMarket` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nmc_vehicleType` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vin_model_id` bigint unsigned DEFAULT NULL,
  `raw_json` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `vin` (`vin`),
  KEY `idx_catalog_code` (`catalogCode`),
  KEY `idx_brand_region` (`brand_id`,`dataRegion`),
  KEY `brand_region_id` (`brand_region_id`),
  KEY `catalog_id` (`catalog_id`),
  KEY `vin_model_id` (`vin_model_id`),
  CONSTRAINT `vin_decoded_cache_ibfk_1` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`) ON DELETE SET NULL,
  CONSTRAINT `vin_decoded_cache_ibfk_2` FOREIGN KEY (`brand_region_id`) REFERENCES `brand_regions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `vin_decoded_cache_ibfk_3` FOREIGN KEY (`catalog_id`) REFERENCES `catalogs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `vin_decoded_cache_ibfk_4` FOREIGN KEY (`vin_model_id`) REFERENCES `vin_models` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=155 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
